### ISSUE TITLE
Two form sections both called "general"

### ISSUE THREAD

**Issue by davidscotson** [turnitin/moodle-mod_turnitintool#12]
The "Advanced Turnitin Options" fieldset on the mod form is called 'general' the same as the standard first section.

This leads to two items on the page with the #id_general, when it should be unique.

This also leads to the section being opened by default, which means users see the advanced settings even when they don't require them.

(I checked to see if this was an issue in the turnitintooltwo mod as well, it only seems to have one 'general' section, but from looking at the code it's possible that it has two sections called 'advanced')

**Comment by jmcgettrick** [comment]
Hi David, we'll get this fixed but we have no current plans for a new release of this plugin so we can't give a date as to when it will be out.

**Comment by jmcgettrick** [comment]
This has been fixed and is in the latest master commit
