### ISSUE TITLE
Agreement checkbox ignored for Moodle 3.0

### ISSUE THREAD

**Issue by marcusysjgreen** [turnitin/moodle-mod_turnitintool#23]
We have mod_turnitintool version 2016030101 installed on Moodle 3.0.4. If the agreement box is unchecked when uploading an item, this is ignored and the item is accepted. This appears to be a change in behaviour to the version we are currently using  2013111404. This version declines to accept and displays an error message that says "You must accept the agreement for this submission"

**Comment by dwinn** [comment]
This has been fixed in the new release today v2016101201.
