### ISSUE TITLE
Coding error when editing assignment part

### ISSUE THREAD

**Issue by CamBanfield** [turnitin/moodle-mod_turnitintool#33]
I know this plugin isn't supported on 3.2 yet but the majority of it appears to be working correctly, apart from one page!

When accessing the assignment then clicking on the "Edit" option to modify the "Assignment Part" the following error is displayed:

Coding error detected, it must be fixed by a programmer: You can not call createFormElement() on the group element that was not yet added to a form.

More information about this error

Debug info: 
Error code: codingerror
Stack trace:
line 153 of /lib/form/group.php: coding_exception thrown
line 150 of /lib/form/datetimeselector.php: call to MoodleQuickForm_group->createFormElement()
line 546 of /lib/pear/HTML/QuickForm/group.php: call to MoodleQuickForm_date_time_selector->_createElements()
line 163 of /lib/pear/HTML/QuickForm/group.php: call to HTML_QuickForm_group->_createElementsIfNotExist()
line 1521 of /mod/turnitintool/lib.php: call to HTML_QuickForm_group->setValue()
line 1703 of /mod/turnitintool/lib.php: call to turnitintool_partform()
line 372 of /mod/turnitintool/view.php: call to turnitintool_introduction()

It appears to be related to the date selectors, as when commented out the page renders fine (but without the dates). 

Moodle version: 3.2+ (Build: 20161215)
Plugin version: 2.6+ 2016122101

**Comment by amclarty** [comment]
@CamBanfield, we're aware of this issue and will fix once we support Moodle 3.2. Thanks for reporting.

**Comment by krazynayba** [comment]
have encountered the same error in Moodle 3.1.

**Comment by dwinn** [comment]
This has been fixed in today's release, v2017031601
