### ISSUE TITLE
2015030304 tag not updated

### ISSUE THREAD

**Issue by sam-moodle** [turnitin/moodle-mod_turnitintool#6]
Hi,

I noticed that it looks like the 2015030304 tag was not updated. The version.php still says 2015030303 and readme has "Release v2015030303" at the top. But if I download from here, https://moodle.org/plugins/pluginversions.php?plugin=mod_turnitintool, I get the new 2015030304 version.

**Comment by jmcgettrick** [comment]
Thanks for pointing that out Sam. I've updated the tag now.
