### ISSUE TITLE
Moodle versions supported

### ISSUE THREAD

**Issue by aspark21** [turnitin/moodle-mod_turnitintool#64]
The README states "The latest Moodle version the plugin currently supports is Moodle 3.1".

We are currently running this on 3.2 and can see some commits to maintain the plugin for 3.2

Also aware that V1 is being retired on 31/12/2018 but in the meantime will this be updated for Moodle 3.4 s we will be upgrading to it in the summer.

So could you clarify what latest version is supported for V1?

**Comment by cwestgarth** [comment]
Hey @aspark21 
Our most recent V1 plugin v2017071901 supports Moodle 3.4. 
More information can be found here: http://turnitin.com/en_us/support/download-integrations

I will let the guys know about the README
Thanks 
Caroline
