### ISSUE TITLE
Table row compacted in Moodle 3.5.x

### ISSUE THREAD

**Issue by troywilliams** [turnitin/moodle-mod_turnitintool#73]
Table TR's are using .row class which is picking up Bootstrap 4 class and setting display to flex which is compacting cells in the row.

Example
![screenshot-uatlearning wintec ac nz-2018 10 17-10-12-37](https://user-images.githubusercontent.com/607907/47048078-ceb59700-d1f5-11e8-9000-e68ab45e8451.png)

**Comment by jmcgettrick** [comment]
Change is now in develop.
