### ISSUE TITLE
Submission Feedback Studio 'Insecure Content Blocked' problem in Chrome

### ISSUE THREAD

**Issue by SeadOak-Dan** [turnitin/moodle-mod_turnitintool#80]
A non-https URL in the Submission Feedback Studio is causing problems on Google Chrome. When a user clicks on a submission, the pop-up doesn't display anything, and a warning appears in the top right with 'Insecure content blocked'. Looking at the DevTools, this error appears: 
"Mixed Content: The page at 'about:blank' was loaded over HTTPS, but requested an insecure resource 'http://ev.turnitinuk.com/auth/ev/d1c45a05e560767e0d0268ae363fb2f1?o=111690319&lang=en_us&u=8445738&s=3'. This request has been blocked; the content must be served over HTTPS."

**Comment by CharlotteSpinks** [comment]
Hi @SeadOak-Dan Thank you for your report of this, we have been working to resolve this issue this morning. I apologise for the inconvenience, this will be resolved ASAP.

**Comment by CharlotteSpinks** [comment]
This issue is now resolved.
